const data = {
    users: [
        {
            name: 'Rahim Ahmed',
            email: 'rahim@example.com',
            password: 'password123',
            phone: '01711111111',
            address: 'Sylhet, Bangladesh',
        },
        {
            name: 'Karim Uddin',
            email: 'karim@example.com',
            password: 'password123',
            phone: '01822222222',
            address: 'Dhaka, Bangladesh',
        },
        {
            name: 'Nusrat Jahan',
            email: 'nusrat@example.com',
            password: 'password123',
            phone: '01933333333',
            address: 'Chittagong, Bangladesh',
        },
        {
            name: 'Tanvir Hasan',
            email: 'tanvir@example.com',
            password: 'password123',
            phone: '01644444444',
            address: 'Khulna, Bangladesh',
        },
        {
            name: 'Mehedi Hassan',
            email: 'bssshoumi@gmail.com',
            password: 'password123',
            phone: '01555555555',
            address: 'Rajshahi, Bangladesh',
            isAdmin: true,
        },
    ],
    products: [
        {
            name: 'Aurora Noise-Canceling Headphones',
            description:
                'Studio-grade sound, 40h battery, plush memory foam ear cups, and adaptive ANC for travel and focus. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            price: 249.99,
            category: 'Electronics',
            brand: 'Aurora Audio',
            image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
            images: [
                'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
                'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&q=80',
            ],
            countInStock: 24,
            rating: 4.8,
            numReviews: 312,
            featured: true,
        },
        {
            name: 'Pulse Smartwatch Pro',
            description:
                'AMOLED display, SpO2, GPS, swim-proof, 7-day battery, and seamless phone notifications. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            price: 329,
            category: 'Electronics',
            brand: 'Pulse',
            image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
            countInStock: 18,
            rating: 4.6,
            numReviews: 189,
            featured: true,
        },
        {
            name: 'Lumina 14" Laptop',
            description: 'Thin aluminum chassis, 16GB RAM, 512GB SSD, all-day battery — built for creators.',
            price: 1199,
            category: 'Electronics',
            brand: 'Lumina',
            image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80',
            countInStock: 10,
            rating: 4.7,
            numReviews: 94,
            featured: true,
        },
        {
            name: 'Retro Film Camera',
            description: '35mm manual camera with leather grip. Perfect for street and travel photography. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            price: 189,
            category: 'Electronics',
            brand: 'RetroCam',
            image: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&q=80',
            countInStock: 15,
            rating: 4.5,
            numReviews: 67,
            featured: false,
        },
        {
            name: 'Velvet Evening Jacket',
            description: 'Tailored velvet blazer with satin lapels. Statement piece for nights out.',
            price: 189.5,
            category: 'Fashion',
            brand: 'Noir Atelier',
            image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&q=80',
            countInStock: 22,
            rating: 4.6,
            numReviews: 41,
            featured: true,
        },
        {
            name: 'Merino Wool Crewneck',
            description: 'Ultra-soft merino, temperature regulating, available in curated earth tones. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            price: 79,
            category: 'Fashion',
            brand: 'North Fold',
            image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80',
            countInStock: 45,
            rating: 4.4,
            numReviews: 128,
            featured: false,
        },
        {
            name: 'Artisan Leather Tote',
            description: 'Full-grain leather, reinforced stitching, fits a 13" laptop and daily essentials.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            price: 265,
            category: 'Fashion',
            brand: 'Atelier Lane',
            image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80',
            countInStock: 12,
            rating: 4.9,
            numReviews: 56,
            featured: true,
        },
        {
            name: 'Minimal Running Sneakers',
            description: 'Lightweight knit upper, responsive foam midsole, grippy rubber outsole. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            price: 139,
            category: 'Fashion',
            brand: 'Stride',
            image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
            countInStock: 60,
            rating: 4.7,
            numReviews: 402,
            featured: false,
        },
        {
            name: 'Ceramic Table Lamp',
            description: 'Hand-glazed ceramic base, warm dimmable LED, brass accents. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.' ,
            price: 112,
            category: 'Home & Living',
            brand: 'Hearth & Co',
            image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80',
            countInStock: 30,
            rating: 4.5,
            numReviews: 88,
            featured: false,
        },
        {
            name: 'Linen Throw Blanket',
            description: 'Breathable European linen, pre-washed for softness, oversized for sofas. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            price: 95,
            category: 'Home & Living',
            brand: 'Hearth & Co',
            image: 'https://images.unsplash.com/photo-1580301762395-7ce25d2f7c4e?w=800&q=80',
            countInStock: 40,
            rating: 4.6,
            numReviews: 73,
            featured: true,
        },
        {
            name: 'Sculptural Vase Set',
            description: 'Set of 3 matte stoneware vases — organic shapes for shelves and dining tables. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            price: 68,
            category: 'Home & Living',
            brand: 'Forma',
            image: 'https://images.unsplash.com/photo-1578500494199-246c612abc35?w=800&q=80',
            countInStock: 25,
            rating: 4.3,
            numReviews: 29,
            featured: false,
        },
        {
            name: 'Carbon Road Bike',
            description: 'Carbon frame, hydraulic disc brakes, Shimano groupset — race-ready geometry. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            price: 2899,
            category: 'Sports',
            brand: 'Velocity',
            image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&q=80',
            countInStock: 6,
            rating: 4.9,
            numReviews: 44,
            featured: true,
        },
        {
            name: 'Yoga Mat Pro',
            description: '5mm natural rubber, alignment lines, non-slip even when hot. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            price: 72,
            category: 'Sports',
            brand: 'ZenFlow',
            image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&q=80',
            countInStock: 55,
            rating: 4.7,
            numReviews: 201,
            featured: false,
        },
        {
            name: 'Adjustable Dumbbells',
            description: 'Quick-dial weight from 5–50 lb per hand. Compact home gym solution. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            price: 399,
            category: 'Sports',
            brand: 'IronCore',
            image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80',
            countInStock: 14,
            rating: 4.8,
            numReviews: 156,
            featured: false,
        },
        {
            name: 'Botanical Face Serum',
            description: 'Vitamin C, hyaluronic acid, cold-pressed botanicals. Brightens and hydrates. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            price: 48,
            category: 'Beauty',
            brand: 'Bloom Labs',
            image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80',
            countInStock: 80,
            rating: 4.6,
            numReviews: 512,
            featured: true,
        },
        {
            name: 'Satin Lip Set',
            description: 'Six wearable shades, creamy satin finish, enriched with shea butter. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            price: 42,
            category: 'Beauty',
            brand: 'Bloom Labs',
            image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80',
            countInStock: 100,
            rating: 4.4,
            numReviews: 233,
            featured: false,
        },
        {
            name: 'Obsidian Eau de Parfum',
            description: 'Smoky oud, black tea, and amber. Long-lasting unisex fragrance. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            price: 128,
            category: 'Beauty',
            brand: 'Noir Atelier',
            image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80',
            countInStock: 35,
            rating: 4.8,
            numReviews: 91,
            featured: true,
        },
        {
            name: 'Design Systems Handbook',
            description: 'Practical guide to scalable UI, tokens, and team workflows — hardcover. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            price: 39.99,
            category: 'Books',
            brand: 'Press Nine',
            image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80',
            countInStock: 120,
            rating: 4.7,
            numReviews: 310,
            featured: false,
        },
        {
            name: 'World Atlas (Illustrated)',
            description: 'Oversized maps, cultural essays, and archival photography. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            price: 65,
            category: 'Books',
            brand: 'Carta',
            image: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=800&q=80',
            countInStock: 48,
            rating: 4.5,
            numReviews: 77,
            featured: false,
        },
        {
            name: 'Sci-Fi Short Stories',
            description: 'Curated anthology from award-winning authors. Pocket edition. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            price: 18.5,
            category: 'Books',
            brand: 'Orbit Press',
            image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&q=80',
            countInStock: 200,
            rating: 4.3,
            numReviews: 412,
            featured: false,
        },
    ],
};

module.exports = data;
